import { Toaster } from "@/components/ui/toaster"
import { ClerkProvider } from "@clerk/nextjs"
import type { Metadata } from "next"
import "./globals.css"
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
}

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<head>
					<link rel="stylesheet" href="https://use.typekit.net/gnn8txw.css" />
				</head>
				<body>
					{children}
					<Toaster />
				</body>
			</html>
		</ClerkProvider>
	)
}
