"use client"

import { useState } from "react"

const PROMPTS = ["What should we do in Manhattan Beach today?", "Plan a day in Santa Monica and Venice", "How should we get here from LAX?", "Plan a Malibu day trip", "Where should we eat nearby?", "What can we do with kids?", "What beaches should we visit?"]
type Message = { role: "user" | "assistant"; text: string }

export function Concierge() {
	const [open, setOpen] = useState(false); const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(""); const [loading, setLoading] = useState(false)
	async function ask(question: string) { if (!question.trim() || loading) return; setMessages((items) => [...items, { role: "user", text: question }]); setInput(""); setLoading(true); try { const response = await fetch("/api/concierge", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: question }) }); const result = await response.json() as { answer?: string }; setMessages((items) => [...items, { role: "assistant", text: result.answer ?? "I’m unable to answer that just now." }]) } catch { setMessages((items) => [...items, { role: "assistant", text: "I’m having trouble connecting right now. The Local Guide is still here to help you plan." }]) } finally { setLoading(false) } }
	return <><button type="button" onClick={() => setOpen(true)} className="bg-[#c2683f] px-7 py-4 text-[12px] uppercase tracking-[.16em] text-white shadow-lg transition hover:bg-[#a9502c]">✨ Ask ShellByTheShore AI</button>{open && <div className="fixed inset-0 z-[110] flex items-end bg-black/45 p-0 sm:items-center sm:justify-center sm:p-6" role="dialog" aria-modal="true" aria-label="ShellByTheShore Local AI Concierge"><div className="flex max-h-[90vh] w-full max-w-xl flex-col bg-[#fdfbf7] shadow-2xl"><div className="flex items-start justify-between border-b border-[#e6ddcf] p-6"><div><p className="text-[11px] uppercase tracking-[.22em] text-[#c2683f]">Your Local AI Concierge</p><h2 className="mt-2 font-serif text-3xl">Ask ShellByTheShore</h2></div><button type="button" onClick={() => setOpen(false)} aria-label="Close concierge" className="p-2 text-2xl">×</button></div><div className="min-h-[250px] flex-1 space-y-4 overflow-y-auto p-6">{messages.length === 0 && <><p className="text-[15px] leading-relaxed text-[#5d6b78]">Thoughtful local help for shaping your South Bay stay. For live hours, availability, or traffic, always check directly before heading out.</p><div className="flex flex-wrap gap-2">{PROMPTS.map((prompt) => <button type="button" key={prompt} onClick={() => void ask(prompt)} className="border border-[#d8cdba] px-3 py-2 text-left text-sm text-[#3d4b57]">{prompt}</button>)}</div></>}{messages.map((message, index) => <p key={`${message.role}-${index}`} className={`max-w-[90%] px-4 py-3 text-[15px] leading-relaxed ${message.role === "user" ? "ml-auto bg-[#28323b] text-white" : "bg-[#f1e4d8] text-[#28323b]"}`}>{message.text}</p>)}{loading && <p className="text-sm text-[#8d7c66]">Thinking about your day by the shore…</p>}</div><form onSubmit={(event) => { event.preventDefault(); void ask(input) }} className="flex gap-2 border-t border-[#e6ddcf] p-4"><input value={input} onChange={(event) => setInput(event.target.value)} className="min-w-0 flex-1 border border-[#d8cdba] bg-white px-3 py-3 text-sm" placeholder="Ask about your stay"/><button disabled={loading} className="bg-[#28323b] px-5 py-3 text-[11px] uppercase tracking-[.16em] text-white disabled:opacity-60">Send</button></form></div></div>}</>
}
