import "server-only"

import { getAirbnbAdvisory } from "@/lib/airbnb-shadow"
import { recalculateCleaningForReservationChange } from "@/lib/cleaning-domain"
import { queryClient } from "@/lib/db"
import { PUBLIC_GUEST_EMAIL } from "@/lib/launch-config"
import { getFromEmail, getTransporter, isSmtpConfigured } from "@/lib/postmark"
import { authorizedHost, classifyUrgency, dollarsToMinor, hostActions } from "@/lib/host-bot-utils"
import { nanoid } from "nanoid"
import { z } from "zod"

const actionSchema = z.object({ updateId: z.string().min(1).max(100), chatId: z.string().min(1).max(100), inquiryId: z.string().min(1).max(100).optional(), shadowEventId: z.string().min(1).max(100).optional(), action: z.enum(hostActions), text: z.string().trim().max(5000).optional(), actorId: z.string().trim().max(100).optional() })
const comparison = (advisory: string, decision: string) => advisory === "UNKNOWN_STALE" ? "STALE" : (advisory === "APPEARS_AVAILABLE") === (decision === "OWNER_VERIFIED_AVAILABLE") ? "MATCH" : "MISMATCH"

export async function applyHostAction(input: unknown) {
	const data = actionSchema.parse(input)
	if (!authorizedHost(data.chatId)) throw new Error("Unauthorized host chat")
	return queryClient.begin(async (tx) => {
		const inquiryId = data.inquiryId ?? null
		const duplicate = await tx`SELECT payload FROM telegram_interactions WHERE update_id=${data.updateId}`
		if (duplicate[0]) return { duplicate: true, ...(duplicate[0].payload as object) }
		const inquiry: Record<string, any> = inquiryId ? ((await tx`SELECT * FROM inquiries WHERE id=${inquiryId} FOR UPDATE`)[0] as Record<string, any> | undefined) ?? {} : {}
		if (inquiryId && !inquiry.id) throw new Error("Inquiry not found")
		if (!inquiryId && !["AIRBNB_STAY_CONFIRMED", "BLOCKED_DATES_ONLY", "IGNORE"].includes(data.action)) throw new Error("Inquiry is required")
		let result: Record<string, unknown> = { action: data.action }
		if (data.action === "REPLY") { await tx`UPDATE inquiries SET telegram_state='AWAITING_REPLY',telegram_draft=NULL,updated_at=now() WHERE id=${inquiryId}`; result = { state: "AWAITING_REPLY", prompt: "Write the reply. It will be previewed before sending." } }
		if (data.action === "AI_DRAFT") {
			if (process.env.HOST_AI_DRAFT_ENABLED !== "true") result = { state: "UNAVAILABLE", message: "AI Draft is not currently available." }
			else { const availability = inquiry.owner_availability_decision ? `The owner verified: ${inquiry.owner_availability_decision}.` : "Do not claim availability; owner verification is still required."; const price = inquiry.quoted_amount_minor ? `The owner-entered price is $${(Number(inquiry.quoted_amount_minor)/100).toFixed(2)} USD.` : "Do not state or invent a price."; const draft = `Hi ${inquiry.guest_first_name},\n\nThank you for your ShellByTheShore inquiry. ${availability} ${price}\n\nBest,\nShellByTheShore`; await tx`UPDATE inquiries SET telegram_state='DRAFT_READY',telegram_draft=${draft},updated_at=now() WHERE id=${inquiryId}`; result = { state: "READY_TO_SEND", draft } }
		}
		if (data.action === "SET_PRICE") { const amount = dollarsToMinor(data.text ?? ""); if (amount === null) throw new Error("Enter a valid USD amount, for example 1250 or 1250.00"); await tx`UPDATE inquiries SET quoted_amount_minor=${amount},quoted_currency='USD',status=CASE WHEN status IN ('NEW','HOST_REVIEW') THEN 'QUOTE_READY' ELSE status END,telegram_state=NULL,updated_at=now() WHERE id=${inquiryId}`; result = { state: "QUOTE_SAVED", amountMinor: amount } }
		if (data.action === "CLEAR_PRICE") { await tx`UPDATE inquiries SET quoted_amount_minor=NULL,quoted_currency=NULL,updated_at=now() WHERE id=${inquiryId}`; result = { state: "PRICE_CLEARED" } }
		if (data.action === "AVAILABLE" || data.action === "NOT_AVAILABLE") { const decision = data.action === "AVAILABLE" ? "OWNER_VERIFIED_AVAILABLE" : "OWNER_VERIFIED_NOT_AVAILABLE"; const latest = await getAirbnbAdvisory(inquiry.check_in as string, inquiry.check_out as string); await tx`UPDATE inquiries SET owner_availability_decision=${decision},owner_verified_at=now(),advisory_at_verification=${latest.advisory},airbnb_sync_at_verification=${latest.lastSuccessfulSync?.toISOString() ?? null}::timestamptz,status=${data.action},updated_at=now() WHERE id=${inquiryId}`; await tx`INSERT INTO availability_reliability_records (id,inquiry_id,advisory,owner_decision,airbnb_last_sync_at,stale_at_decision,comparison_result) VALUES (${nanoid()},${inquiryId},${latest.advisory},${decision},${latest.lastSuccessfulSync?.toISOString() ?? null}::timestamptz,${latest.advisory === "UNKNOWN_STALE"},${comparison(latest.advisory, decision)})`; result = { state: decision, advisory: latest.advisory, manualVerification: true } }
		if (data.action === "MARK_REPLIED") { await tx`UPDATE inquiries SET status='REPLIED',replied_at=COALESCE(replied_at,now()),updated_at=now() WHERE id=${inquiryId}`; result = { state: "REPLIED", emailSent: false } }
		if (data.action === "GUEST_CONFIRMED") { await tx`UPDATE inquiries SET telegram_state='CONFIRM_GUEST_PENDING',updated_at=now() WHERE id=${inquiryId}`; result = { state: "CONFIRM_MANUAL_STAY", confirmationRequired: true } }
		if (data.action === "CONFIRM_GUEST") { if (inquiry.telegram_state !== "CONFIRM_GUEST_PENDING") throw new Error("Second confirmation required"); await tx`UPDATE inquiries SET status='CONFIRMED_MANUAL',confirmed_at=now(),telegram_state=NULL,updated_at=now() WHERE id=${inquiryId}`; result = { state: "CONFIRMED_MANUAL", paymentStatus: "UNPAID" } }
		if (data.action === "CREATE_BOOKING") { if (inquiry.status !== "CONFIRMED_MANUAL") throw new Error("Confirm the manual stay first"); await tx`UPDATE inquiries SET telegram_state='CREATE_BOOKING_PENDING',updated_at=now() WHERE id=${inquiryId}`; result = { state: "CREATE_BOOKING_PREVIEW", confirmationRequired: true, paymentStatus: "UNPAID" } }
		if (data.action === "CONFIRM_CREATE_BOOKING") { if (inquiry.telegram_state !== "CREATE_BOOKING_PENDING") throw new Error("Explicit booking confirmation required"); const existing = await tx`SELECT id FROM reservations WHERE client_request_id=${`INQUIRY:${inquiryId}`}`; let reservationId = existing[0]?.id as string | undefined; if (!reservationId) { reservationId = nanoid(); const amount = Number(inquiry.quoted_amount_minor ?? 0); await tx`INSERT INTO reservations (id,confirmation_code,property_id,booking_source,client_request_id,guest_first_name,guest_last_name,guest_email,guest_phone,check_in,check_out,adults,children,total_guests,booking_status,payment_status,currency,subtotal,cleaning_fee,taxes,discount_amount,total_amount,amount_due,price_snapshot,confirmed_at) VALUES (${reservationId},${`SBS-${nanoid(10).toUpperCase()}`},${inquiry.property_id},'DIRECT_MANUAL',${`INQUIRY:${inquiryId}`},${inquiry.guest_first_name},${inquiry.guest_last_name},${inquiry.email},${inquiry.phone},${inquiry.check_in}::date,${inquiry.check_out}::date,${inquiry.guests},0,${inquiry.guests},'CONFIRMED','UNPAID','USD',${amount},0,0,0,${amount},${amount},${JSON.stringify({ source: "OWNER_CONFIRMED_INQUIRY", inquiryReference: inquiry.public_reference })}::jsonb,now())`; await tx`UPDATE inquiries SET status='BOOKING_CREATED',telegram_state=NULL,updated_at=now() WHERE id=${inquiryId}`; } result = { state: "BOOKING_CREATED", reservationId, charged: false } }
		if (data.action === "SEND_DRAFT") { if (inquiry.telegram_state !== "DRAFT_READY" || !inquiry.telegram_draft) throw new Error("A previewed draft is required"); if (!isSmtpConfigured()) throw new Error("SMTP is not configured"); const subject = `Re: ShellByTheShore Availability — ${inquiry.public_reference}`; const info = await getTransporter().sendMail({ from: { name: process.env.SMTP_FROM_NAME || "ShellByTheShore", address: getFromEmail() || PUBLIC_GUEST_EMAIL }, to: inquiry.email as string, subject, text: inquiry.telegram_draft as string, inReplyTo: inquiry.email_thread_message_id || undefined, references: inquiry.email_thread_message_id || undefined }); await tx`INSERT INTO inquiry_messages (id,inquiry_id,direction,subject,content_plain,message_id,in_reply_to,owner_identity,sent_at) VALUES (${nanoid()},${inquiryId},'OUTBOUND',${subject},${inquiry.telegram_draft},${info.messageId || null},${inquiry.email_thread_message_id || null},${data.actorId || data.chatId},now())`; await tx`UPDATE inquiries SET status='REPLIED',replied_at=now(),telegram_state=NULL,telegram_draft=NULL,updated_at=now() WHERE id=${inquiryId}`; result = { state: "EMAIL_SENT", messageId: info.messageId } }
		if (data.action === "CANCEL") { await tx`UPDATE inquiries SET telegram_state=NULL,telegram_draft=NULL,updated_at=now() WHERE id=${inquiryId}`; result = { state: "CANCELLED" } }
		if (["AIRBNB_STAY_CONFIRMED", "BLOCKED_DATES_ONLY", "IGNORE"].includes(data.action)) { if (!data.shadowEventId) throw new Error("Shadow event is required"); await tx`UPDATE airbnb_shadow_events SET owner_classification=${data.action},owner_verified_at=now(),owner_verification_result=${data.action} WHERE id=${data.shadowEventId}`; result = { state: data.action } }
		await tx`INSERT INTO telegram_interactions (update_id,chat_id,inquiry_id,action,state,payload) VALUES (${data.updateId},${data.chatId},${data.inquiryId ?? null},${data.action},${String(result.state ?? "DONE")},${JSON.stringify(result)}::jsonb)`
		return result
	}).then(async (result) => { if (result.state === "BOOKING_CREATED" && typeof result.reservationId === "string") await recalculateCleaningForReservationChange(result.reservationId, "MANUAL_BOOKING_CREATED").catch(() => null); return result })
}

export { authorizedHost, classifyUrgency, dollarsToMinor, hostActions }
