import { auth } from "@clerk/nextjs/server"
import { queryClient } from "@/lib/db"
import Link from "next/link"

export const metadata = { title: "Booking calendar | ShellByTheShore", robots: { index: false, follow: false } }

export default async function BookingCalendarPage() {
	const { userId } = await auth()
	if (!userId) return <main className="min-h-screen bg-[#fdfbf7] px-5 py-20 text-[#28323b]"><h1 className="font-serif text-4xl">Owner access required</h1><Link className="mt-6 inline-block underline" href="/dashboard">Sign in to open booking operations</Link></main>
	try {
		const rows = await queryClient`SELECT r.id, r.confirmation_code, r.booking_source, r.check_in::text, r.check_out::text, r.booking_status, r.payment_status, r.total_amount, r.currency, p.name AS property_name FROM reservations r JOIN properties p ON p.id=r.property_id WHERE p.clerk_id=${userId} AND r.check_out >= current_date - interval '30 days' ORDER BY r.check_in ASC LIMIT 200`
		return <main className="min-h-screen bg-[#fdfbf7] px-5 py-14 text-[#28323b] sm:px-8 lg:px-14"><Link href="/dashboard" className="text-sm underline underline-offset-4">← Owner dashboard</Link><p className="mt-10 text-[11px] uppercase tracking-[.24em] text-[#8d7c66]">Owner operations</p><h1 className="mt-3 font-serif text-5xl">Booking calendar</h1><p className="mt-4 max-w-2xl leading-relaxed text-[#5d6b78]">Direct reservations, temporary holds, and normalized external calendar blocks appear here. Guest names and payment details are deliberately not shown in this calendar overview.</p><div className="mt-10 overflow-x-auto border border-[#e6ddcf] bg-white"><table className="min-w-full text-left text-sm"><thead className="border-b border-[#e6ddcf] text-[11px] uppercase tracking-[.14em] text-[#8d7c66]"><tr><th className="p-4">Property</th><th className="p-4">Stay</th><th className="p-4">Source</th><th className="p-4">Status</th><th className="p-4">Payment</th><th className="p-4">Total</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id as string} className="border-b border-[#f0e9df]"><td className="p-4">{row.property_name as string}</td><td className="p-4">{row.check_in as string} → {row.check_out as string}<span className="mt-1 block text-xs text-[#8d7c66]">{row.confirmation_code as string}</span></td><td className="p-4">{row.booking_source as string}</td><td className="p-4">{row.booking_status as string}</td><td className="p-4">{row.payment_status as string}</td><td className="p-4">{new Intl.NumberFormat("en-US", { style: "currency", currency: row.currency as string }).format(Number(row.total_amount) / 100)}</td></tr>)}{rows.length === 0 && <tr><td className="p-6 text-[#5d6b78]" colSpan={6}>No booking or calendar blocks are currently available for your properties.</td></tr>}</tbody></table></div><p className="mt-6 text-sm text-[#5d6b78]">Inbound Airbnb and OTA iCal synchronization remains disabled until verified calendar URLs and reconciliation settings are configured.</p></main>
	} catch {
		return <main className="min-h-screen bg-[#fdfbf7] px-5 py-20 text-[#28323b]"><Link href="/dashboard" className="text-sm underline">← Owner dashboard</Link><h1 className="mt-8 font-serif text-4xl">Booking calendar setup required</h1><p className="mt-4 max-w-xl leading-relaxed text-[#5d6b78]">Apply the direct-booking migration before using owner booking operations.</p></main>
	}
}
